% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={R-Happiness-Index-Model},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{R-Happiness-Index-Model}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readr)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'ggplot2' was built under R version 4.1.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(datasets)}
\FunctionTok{library}\NormalTok{(Hmisc)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: lattice
\end{verbatim}

\begin{verbatim}
## Loading required package: survival
\end{verbatim}

\begin{verbatim}
## Loading required package: Formula
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'Hmisc'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     format.pval, units
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{world.happiness }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"2015.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(world.happiness)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Country             Region          Happiness.Rank   Happiness.Score
##  Length:158         Length:158         Min.   :  1.00   Min.   :2.839  
##  Class :character   Class :character   1st Qu.: 40.25   1st Qu.:4.526  
##  Mode  :character   Mode  :character   Median : 79.50   Median :5.232  
##                                        Mean   : 79.49   Mean   :5.376  
##                                        3rd Qu.:118.75   3rd Qu.:6.244  
##                                        Max.   :158.00   Max.   :7.587  
##  Standard.Error    Economy..GDP.per.Capita.     Family      
##  Min.   :0.01848   Min.   :0.0000           Min.   :0.0000  
##  1st Qu.:0.03727   1st Qu.:0.5458           1st Qu.:0.8568  
##  Median :0.04394   Median :0.9102           Median :1.0295  
##  Mean   :0.04788   Mean   :0.8461           Mean   :0.9910  
##  3rd Qu.:0.05230   3rd Qu.:1.1584           3rd Qu.:1.2144  
##  Max.   :0.13693   Max.   :1.6904           Max.   :1.4022  
##  Health..Life.Expectancy.    Freedom       Trust..Government.Corruption.
##  Min.   :0.0000           Min.   :0.0000   Min.   :0.00000              
##  1st Qu.:0.4392           1st Qu.:0.3283   1st Qu.:0.06168              
##  Median :0.6967           Median :0.4355   Median :0.10722              
##  Mean   :0.6303           Mean   :0.4286   Mean   :0.14342              
##  3rd Qu.:0.8110           3rd Qu.:0.5491   3rd Qu.:0.18025              
##  Max.   :1.0252           Max.   :0.6697   Max.   :0.55191              
##    Generosity     Dystopia.Residual
##  Min.   :0.0000   Min.   :0.3286   
##  1st Qu.:0.1506   1st Qu.:1.7594   
##  Median :0.2161   Median :2.0954   
##  Mean   :0.2373   Mean   :2.0990   
##  3rd Qu.:0.3099   3rd Qu.:2.4624   
##  Max.   :0.7959   Max.   :3.6021
\end{verbatim}

\#OBSERVATION: \#There are no NA's or inaccurate observations so we do
not need to screen for accuracy.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(world.happiness)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    158 obs. of  12 variables:
##  $ Country                      : chr  "Switzerland" "Iceland" "Denmark" "Norway" ...
##  $ Region                       : chr  "Western Europe" "Western Europe" "Western Europe" "Western Europe" ...
##  $ Happiness.Rank               : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Happiness.Score              : num  7.59 7.56 7.53 7.52 7.43 ...
##  $ Standard.Error               : num  0.0341 0.0488 0.0333 0.0388 0.0355 ...
##  $ Economy..GDP.per.Capita.     : num  1.4 1.3 1.33 1.46 1.33 ...
##  $ Family                       : num  1.35 1.4 1.36 1.33 1.32 ...
##  $ Health..Life.Expectancy.     : num  0.941 0.948 0.875 0.885 0.906 ...
##  $ Freedom                      : num  0.666 0.629 0.649 0.67 0.633 ...
##  $ Trust..Government.Corruption.: num  0.42 0.141 0.484 0.365 0.33 ...
##  $ Generosity                   : num  0.297 0.436 0.341 0.347 0.458 ...
##  $ Dystopia.Residual            : num  2.52 2.7 2.49 2.47 2.45 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Checking the degrees of freedom for the mahalanobis cutoff. }
\CommentTok{\#Summarizing mahal scores that are greater than the cutoff. }
\CommentTok{\#Checking the cut off score for our Mahalanobis measure.}

\NormalTok{mahal }\OtherTok{=} \FunctionTok{mahalanobis}\NormalTok{(world.happiness[, }\DecValTok{3}\SpecialCharTok{:}\DecValTok{12}\NormalTok{], }\FunctionTok{colMeans}\NormalTok{(world.happiness[, }\DecValTok{3}\SpecialCharTok{:}\DecValTok{12}\NormalTok{]), }\FunctionTok{cov}\NormalTok{(world.happiness[, }\DecValTok{3}\SpecialCharTok{:}\DecValTok{12}\NormalTok{], }\AttributeTok{use =} \StringTok{"pairwise.complete.obs"}\NormalTok{))}

\NormalTok{cutoff }\OtherTok{=} \FunctionTok{qchisq}\NormalTok{(}\DecValTok{1}\FloatTok{{-}0.001}\NormalTok{, }\FunctionTok{ncol}\NormalTok{(world.happiness[, }\DecValTok{3}\SpecialCharTok{:}\DecValTok{12}\NormalTok{]))}
\NormalTok{cutoff}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 29.5883
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(mahal }\SpecialCharTok{\textless{}}\NormalTok{ cutoff)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Mode   FALSE    TRUE 
## logical       3     155
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Plotting the variable Economy GDP per Capita as the predictor of the Happiness Score}
\CommentTok{\#Plotting the variable Life Expectancy as the predictor of the Happiness Score}

\CommentTok{\#Graphing the relationship between Economy GDP per Capita and Happiness Score}

\NormalTok{m1 }\OtherTok{=} \FunctionTok{lm}\NormalTok{(world.happiness}\SpecialCharTok{$}\NormalTok{Happiness.Score }\SpecialCharTok{\textasciitilde{}}\NormalTok{ world.happiness}\SpecialCharTok{$}\NormalTok{Economy..GDP.per.Capita.)}
\FunctionTok{summary}\NormalTok{(m1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = world.happiness$Happiness.Score ~ world.happiness$Economy..GDP.per.Capita.)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.96394 -0.48777 -0.07157  0.55947  1.60705 
## 
## Coefficients:
##                                          Estimate Std. Error t value Pr(>|t|)
## (Intercept)                                 3.499      0.133   26.30   <2e-16
## world.happiness$Economy..GDP.per.Capita.    2.218      0.142   15.62   <2e-16
##                                             
## (Intercept)                              ***
## world.happiness$Economy..GDP.per.Capita. ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.7174 on 156 degrees of freedom
## Multiple R-squared:  0.6099, Adjusted R-squared:  0.6074 
## F-statistic: 243.9 on 1 and 156 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(world.happiness}\SpecialCharTok{$}\NormalTok{Economy..GDP.per.Capita., world.happiness}\SpecialCharTok{$}\NormalTok{Happiness.Score)}
\end{Highlighting}
\end{Shaded}

\includegraphics{R-Happiness-Index-Model_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{\{}\FunctionTok{plot}\NormalTok{(world.happiness}\SpecialCharTok{$}\NormalTok{Economy..GDP.per.Capita.}\SpecialCharTok{\textasciitilde{}}\NormalTok{ world.happiness}\SpecialCharTok{$}\NormalTok{Happiness.Score)}
  \FunctionTok{abline}\NormalTok{(}\FunctionTok{lm}\NormalTok{(world.happiness}\SpecialCharTok{$}\NormalTok{Economy..GDP.per.Capita.}\SpecialCharTok{\textasciitilde{}}\NormalTok{ world.happiness}\SpecialCharTok{$}\NormalTok{Happiness.Score))\}}
\end{Highlighting}
\end{Shaded}

\includegraphics{R-Happiness-Index-Model_files/figure-latex/unnamed-chunk-5-2.pdf}
\#OBSERVATION- The relationship is linear between the Economy of a
country and the Happiness Score

\#Looking at the correlation coefficient to quantify the strength of the
relationship

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(world.happiness}\SpecialCharTok{$}\NormalTok{Economy..GDP.per.Capita., world.happiness}\SpecialCharTok{$}\NormalTok{Happiness.Score)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7809655
\end{verbatim}

\#Correlation coefficient for happiness score and Economy is 0.781

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{\{}\FunctionTok{plot}\NormalTok{(world.happiness}\SpecialCharTok{$}\NormalTok{Health..Life.Expectancy. }\SpecialCharTok{\textasciitilde{}}\NormalTok{ world.happiness}\SpecialCharTok{$}\NormalTok{Happiness.Score)}
  \FunctionTok{abline}\NormalTok{(}\FunctionTok{lm}\NormalTok{(world.happiness}\SpecialCharTok{$}\NormalTok{Health..Life.Expectancy. }\SpecialCharTok{\textasciitilde{}}\NormalTok{ world.happiness}\SpecialCharTok{$}\NormalTok{Happiness.Score))\}}
\end{Highlighting}
\end{Shaded}

\includegraphics{R-Happiness-Index-Model_files/figure-latex/unnamed-chunk-7-1.pdf}
OBSERVATION- The relationship is linear

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Looking at the correlation coefficient to quantify the strength of the relationship}

\FunctionTok{cor}\NormalTok{(world.happiness}\SpecialCharTok{$}\NormalTok{Health..Life.Expectancy., world.happiness}\SpecialCharTok{$}\NormalTok{Happiness.Score)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7241996
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#The correlation coefficient for happiness score and life expectancy is 0.724}

\CommentTok{\#Plotting the correlation of the world happiness score against the independent variables}
\NormalTok{corrplot}\SpecialCharTok{::}\FunctionTok{corrplot}\NormalTok{(}\FunctionTok{cor}\NormalTok{(world.happiness[, }\DecValTok{3}\SpecialCharTok{:}\DecValTok{12}\NormalTok{]))}
\end{Highlighting}
\end{Shaded}

\includegraphics{R-Happiness-Index-Model_files/figure-latex/unnamed-chunk-8-1.pdf}
Sum of Squared Residuals

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#plot\_ss(x = world.happiness$Economy..GDP.per.Capita., y = world.happiness$Happiness.Score)}

\CommentTok{\#plot\_ss(x = world.happiness$Economy..GDP.per.Capita., y = world.happiness$Happiness.Score, showSquares = TRUE)}

\CommentTok{\#Fitting the linar model (regression line)}

\NormalTok{m2 }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Happiness.Score }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Economy..GDP.per.Capita., }\AttributeTok{data =}\NormalTok{ world.happiness)}

\FunctionTok{summary}\NormalTok{(m2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Happiness.Score ~ Economy..GDP.per.Capita., data = world.happiness)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.96394 -0.48777 -0.07157  0.55947  1.60705 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(>|t|)    
## (Intercept)                 3.499      0.133   26.30   <2e-16 ***
## Economy..GDP.per.Capita.    2.218      0.142   15.62   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.7174 on 156 degrees of freedom
## Multiple R-squared:  0.6099, Adjusted R-squared:  0.6074 
## F-statistic: 243.9 on 1 and 156 DF,  p-value: < 2.2e-16
\end{verbatim}

OBSERVATION-

\#The Cofficient's table in the summary fuction of m2 shows the linear
model's y-intercept and the coefficient of Economy GDP per Capita.
\#Therefore the least squares regression line for the linear model of
Happiness Score is: \#Happiness Score = 3.499 + 2.218*
Economy..GDP.per.capita

\#Multiple R-squared representsthe proportion of variability in the
response variable that is explained by the explanatory variable, For
this model 60.9\% of the variability in the Happiness Score is explained
by Economy GDP Per Capita.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Checking to see if the linear model is reliable}

\CommentTok{\#The relationship between Happiness Score and Economy GDP per Capita was linear }
\CommentTok{\#We will now verify this condition with the residuals vs GDP per Capita}

\NormalTok{\{}\FunctionTok{plot}\NormalTok{(m1}\SpecialCharTok{$}\NormalTok{residuals }\SpecialCharTok{\textasciitilde{}}\NormalTok{ world.happiness}\SpecialCharTok{$}\NormalTok{Economy..GDP.per.Capita.)}
  \FunctionTok{abline}\NormalTok{(}\AttributeTok{h =} \DecValTok{0}\NormalTok{, }\AttributeTok{lty =} \DecValTok{3}\NormalTok{)\}}
\end{Highlighting}
\end{Shaded}

\includegraphics{R-Happiness-Index-Model_files/figure-latex/unnamed-chunk-10-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(m1}\SpecialCharTok{$}\NormalTok{residuals)}
\end{Highlighting}
\end{Shaded}

\includegraphics{R-Happiness-Index-Model_files/figure-latex/unnamed-chunk-11-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{\{}\FunctionTok{qqnorm}\NormalTok{(m1}\SpecialCharTok{$}\NormalTok{residuals)}
  \FunctionTok{qqline}\NormalTok{(m1}\SpecialCharTok{$}\NormalTok{residuals)\}}
\end{Highlighting}
\end{Shaded}

\includegraphics{R-Happiness-Index-Model_files/figure-latex/unnamed-chunk-12-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Checking the best predictor for Happiness Score}
\FunctionTok{summary}\NormalTok{(}\FunctionTok{lm}\NormalTok{(Happiness.Score }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Economy..GDP.per.Capita., }\AttributeTok{data =}\NormalTok{ world.happiness))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Happiness.Score ~ Economy..GDP.per.Capita., data = world.happiness)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.96394 -0.48777 -0.07157  0.55947  1.60705 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(>|t|)    
## (Intercept)                 3.499      0.133   26.30   <2e-16 ***
## Economy..GDP.per.Capita.    2.218      0.142   15.62   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.7174 on 156 degrees of freedom
## Multiple R-squared:  0.6099, Adjusted R-squared:  0.6074 
## F-statistic: 243.9 on 1 and 156 DF,  p-value: < 2.2e-16
\end{verbatim}

\#Multiple R Squared = 60.1\%

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(}\FunctionTok{lm}\NormalTok{(Happiness.Score }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Family, }\AttributeTok{data =}\NormalTok{ world.happiness))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Happiness.Score ~ Family, data = world.happiness)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.88667 -0.47443 -0.02976  0.61584  2.04955 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   2.2902     0.2324   9.855   <2e-16 ***
## Family        3.1134     0.2262  13.766   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.7718 on 156 degrees of freedom
## Multiple R-squared:  0.5485, Adjusted R-squared:  0.5456 
## F-statistic: 189.5 on 1 and 156 DF,  p-value: < 2.2e-16
\end{verbatim}

\#Multiple R Squared = 54.9\%

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(}\FunctionTok{lm}\NormalTok{(Happiness.Score }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Freedom, }\AttributeTok{data =}\NormalTok{ world.happiness))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Happiness.Score ~ Freedom, data = world.happiness)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.61618 -0.64097  0.02194  0.82129  1.96886 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   3.5252     0.2274  15.505  < 2e-16 ***
## Freedom       4.3174     0.5006   8.624 6.88e-15 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.9452 on 156 degrees of freedom
## Multiple R-squared:  0.3229, Adjusted R-squared:  0.3185 
## F-statistic: 74.38 on 1 and 156 DF,  p-value: 6.876e-15
\end{verbatim}

\#Multiple R Squared = 32.3\%

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(}\FunctionTok{lm}\NormalTok{(Happiness.Score }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Generosity, }\AttributeTok{data =}\NormalTok{ world.happiness))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Happiness.Score ~ Generosity, data = world.happiness)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.7519 -0.8244 -0.1017  0.8179  2.1143 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   4.9890     0.1913   26.07   <2e-16 ***
## Generosity    1.6298     0.7118    2.29   0.0234 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.13 on 156 degrees of freedom
## Multiple R-squared:  0.03251,    Adjusted R-squared:  0.02631 
## F-statistic: 5.243 on 1 and 156 DF,  p-value: 0.02338
\end{verbatim}

\#Multiple R Squared = 0.33\%

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(}\FunctionTok{lm}\NormalTok{(Happiness.Score }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Region, }\AttributeTok{data =}\NormalTok{ world.happiness))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Happiness.Score ~ Region, data = world.happiness)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.40090 -0.41482  0.03294  0.49507  1.87110 
## 
## Coefficients:
##                                       Estimate Std. Error t value Pr(>|t|)    
## (Intercept)                             7.2850     0.5268  13.828  < 2e-16 ***
## RegionCentral and Eastern Europe       -1.9521     0.5447  -3.584 0.000459 ***
## RegionEastern Asia                     -1.6588     0.6083  -2.727 0.007166 ** 
## RegionLatin America and Caribbean      -1.1403     0.5502  -2.072 0.039964 *  
## RegionMiddle East and Northern Africa  -1.8781     0.5525  -3.399 0.000869 ***
## RegionNorth America                    -0.0120     0.7450  -0.016 0.987171    
## RegionSoutheastern Asia                -1.9676     0.5824  -3.378 0.000932 ***
## RegionSouthern Asia                    -2.7041     0.5974  -4.527 1.22e-05 ***
## RegionSub-Saharan Africa               -3.0822     0.5398  -5.710 6.00e-08 ***
## RegionWestern Europe                   -0.5954     0.5513  -1.080 0.281948    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.745 on 148 degrees of freedom
## Multiple R-squared:  0.6009, Adjusted R-squared:  0.5766 
## F-statistic: 24.76 on 9 and 148 DF,  p-value: < 2.2e-16
\end{verbatim}

\#Multiple R Squared = 60.1\%

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(}\FunctionTok{lm}\NormalTok{(Happiness.Score }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Health..Life.Expectancy., }\AttributeTok{data =}\NormalTok{ world.happiness))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Happiness.Score ~ Health..Life.Expectancy., data = world.happiness)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.67739 -0.58523  0.05623  0.65077  1.47026 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(>|t|)    
## (Intercept)                3.2605     0.1731   18.83   <2e-16 ***
## Health..Life.Expectancy.   3.3561     0.2559   13.12   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.7921 on 156 degrees of freedom
## Multiple R-squared:  0.5245, Adjusted R-squared:  0.5214 
## F-statistic: 172.1 on 1 and 156 DF,  p-value: < 2.2e-16
\end{verbatim}

\#Multiple R Squared = 52.5\%

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(}\FunctionTok{lm}\NormalTok{(Happiness.Score }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Trust..Government.Corruption., }\AttributeTok{data =}\NormalTok{ world.happiness))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Happiness.Score ~ Trust..Government.Corruption., 
##     data = world.happiness)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.4507 -0.6569 -0.0114  0.8327  2.1927 
## 
## Coefficients:
##                               Estimate Std. Error t value Pr(>|t|)    
## (Intercept)                     4.8351     0.1310  36.898  < 2e-16 ***
## Trust..Government.Corruption.   3.7698     0.7016   5.373 2.76e-07 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.055 on 156 degrees of freedom
## Multiple R-squared:  0.1562, Adjusted R-squared:  0.1508 
## F-statistic: 28.87 on 1 and 156 DF,  p-value: 2.764e-07
\end{verbatim}

\#Multiple R Squared = 15.6\%

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(}\FunctionTok{lm}\NormalTok{(Happiness.Score }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Dystopia.Residual, }\AttributeTok{data =}\NormalTok{ world.happiness))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Happiness.Score ~ Dystopia.Residual, data = world.happiness)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.38169 -0.70740  0.02597  0.63849  1.83025 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(>|t|)    
## (Intercept)         3.0726     0.3047  10.084  < 2e-16 ***
## Dystopia.Residual   1.0973     0.1404   7.816 7.57e-13 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.9737 on 156 degrees of freedom
## Multiple R-squared:  0.2814, Adjusted R-squared:  0.2768 
## F-statistic: 61.09 on 1 and 156 DF,  p-value: 7.571e-13
\end{verbatim}

\#Multiple R Squared = 28.1\%

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Determining the best model fit}
\NormalTok{best.model.fit }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Happiness.Score }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Economy..GDP.per.Capita. }\SpecialCharTok{+}\NormalTok{ Family }\SpecialCharTok{+}\NormalTok{ Region }\SpecialCharTok{+}\NormalTok{ Health..Life.Expectancy., }\AttributeTok{data =}\NormalTok{ world.happiness)}
\FunctionTok{summary}\NormalTok{(best.model.fit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Happiness.Score ~ Economy..GDP.per.Capita. + Family + 
##     Region + Health..Life.Expectancy., data = world.happiness)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.37259 -0.32095 -0.01271  0.35328  1.14602 
## 
## Coefficients:
##                                       Estimate Std. Error t value Pr(>|t|)    
## (Intercept)                            3.52947    0.56836   6.210 5.29e-09 ***
## Economy..GDP.per.Capita.               1.01913    0.22532   4.523 1.26e-05 ***
## Family                                 1.40766    0.23208   6.065 1.09e-08 ***
## RegionCentral and Eastern Europe      -1.09924    0.40815  -2.693  0.00791 ** 
## RegionEastern Asia                    -1.18613    0.44690  -2.654  0.00884 ** 
## RegionLatin America and Caribbean     -0.28382    0.41327  -0.687  0.49333    
## RegionMiddle East and Northern Africa -0.95718    0.41905  -2.284  0.02381 *  
## RegionNorth America                   -0.01698    0.54537  -0.031  0.97520    
## RegionSoutheastern Asia               -0.77344    0.44143  -1.752  0.08186 .  
## RegionSouthern Asia                   -0.77426    0.47546  -1.628  0.10560    
## RegionSub-Saharan Africa              -1.03399    0.47279  -2.187  0.03034 *  
## RegionWestern Europe                  -0.50078    0.40337  -1.241  0.21643    
## Health..Life.Expectancy.               0.63985    0.44146   1.449  0.14938    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.5446 on 145 degrees of freedom
## Multiple R-squared:  0.7911, Adjusted R-squared:  0.7738 
## F-statistic: 45.75 on 12 and 145 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{best.model.fit}\FloatTok{.2} \OtherTok{=} \FunctionTok{lm}\NormalTok{(Happiness.Score }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Economy..GDP.per.Capita. }\SpecialCharTok{+}\NormalTok{ Family }\SpecialCharTok{+}\NormalTok{ Region }\SpecialCharTok{+}\NormalTok{ Health..Life.Expectancy.}\SpecialCharTok{+}\NormalTok{  Freedom }\SpecialCharTok{+}\NormalTok{ Trust..Government.Corruption. }\SpecialCharTok{+}\NormalTok{ Generosity }\SpecialCharTok{+}\NormalTok{ Dystopia.Residual, }\AttributeTok{data =}\NormalTok{ world.happiness)}
\FunctionTok{summary}\NormalTok{(best.model.fit}\FloatTok{.2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Happiness.Score ~ Economy..GDP.per.Capita. + Family + 
##     Region + Health..Life.Expectancy. + Freedom + Trust..Government.Corruption. + 
##     Generosity + Dystopia.Residual, data = world.happiness)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -5.475e-04 -2.129e-04  1.010e-06  2.264e-04  4.723e-04 
## 
## Coefficients:
##                                         Estimate Std. Error   t value Pr(>|t|)
## (Intercept)                           -7.886e-05  3.394e-04    -0.232    0.817
## Economy..GDP.per.Capita.               1.000e+00  1.226e-04  8157.734   <2e-16
## Family                                 1.000e+00  1.255e-04  7965.015   <2e-16
## RegionCentral and Eastern Europe       1.558e-04  2.289e-04     0.681    0.497
## RegionEastern Asia                    -3.365e-06  2.442e-04    -0.014    0.989
## RegionLatin America and Caribbean      1.024e-04  2.259e-04     0.453    0.651
## RegionMiddle East and Northern Africa  3.495e-05  2.278e-04     0.153    0.878
## RegionNorth America                   -1.834e-04  2.852e-04    -0.643    0.521
## RegionSoutheastern Asia                1.050e-05  2.353e-04     0.045    0.964
## RegionSouthern Asia                    2.239e-04  2.521e-04     0.888    0.376
## RegionSub-Saharan Africa               5.301e-05  2.544e-04     0.208    0.835
## RegionWestern Europe                  -3.064e-05  2.143e-04    -0.143    0.886
## Health..Life.Expectancy.               9.998e-01  2.326e-04  4298.518   <2e-16
## Freedom                                9.997e-01  2.156e-04  4636.717   <2e-16
## Trust..Government.Corruption.          1.000e+00  2.413e-04  4144.009   <2e-16
## Generosity                             1.000e+00  2.387e-04  4190.945   <2e-16
## Dystopia.Residual                      1.000e+00  4.619e-05 21651.713   <2e-16
##                                          
## (Intercept)                              
## Economy..GDP.per.Capita.              ***
## Family                                ***
## RegionCentral and Eastern Europe         
## RegionEastern Asia                       
## RegionLatin America and Caribbean        
## RegionMiddle East and Northern Africa    
## RegionNorth America                      
## RegionSoutheastern Asia                  
## RegionSouthern Asia                      
## RegionSub-Saharan Africa                 
## RegionWestern Europe                     
## Health..Life.Expectancy.              ***
## Freedom                               ***
## Trust..Government.Corruption.         ***
## Generosity                            ***
## Dystopia.Residual                     ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.0002828 on 141 degrees of freedom
## Multiple R-squared:      1,  Adjusted R-squared:      1 
## F-statistic: 1.609e+08 on 16 and 141 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{\{}\FunctionTok{qqnorm}\NormalTok{(best.model.fit}\SpecialCharTok{$}\NormalTok{residuals)}
  \FunctionTok{qqline}\NormalTok{(best.model.fit}\SpecialCharTok{$}\NormalTok{residuals)\}}
\end{Highlighting}
\end{Shaded}

\includegraphics{R-Happiness-Index-Model_files/figure-latex/unnamed-chunk-23-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{\{}\FunctionTok{qqnorm}\NormalTok{(best.model.fit}\FloatTok{.2}\SpecialCharTok{$}\NormalTok{residuals)}
  \FunctionTok{qqline}\NormalTok{(best.model.fit}\FloatTok{.2}\SpecialCharTok{$}\NormalTok{residuals)\}}
\end{Highlighting}
\end{Shaded}

\includegraphics{R-Happiness-Index-Model_files/figure-latex/unnamed-chunk-24-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{best.model.fit}\FloatTok{.3} \OtherTok{=} \FunctionTok{lm}\NormalTok{(Happiness.Score }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Economy..GDP.per.Capita. }\SpecialCharTok{+}\NormalTok{ Family }\SpecialCharTok{+}\NormalTok{ Region }\SpecialCharTok{+}\NormalTok{ Health..Life.Expectancy.}\SpecialCharTok{+}\NormalTok{  Freedom }\SpecialCharTok{+}\NormalTok{ Trust..Government.Corruption. }\SpecialCharTok{+}\NormalTok{ Dystopia.Residual, }\AttributeTok{data =}\NormalTok{ world.happiness)}
\FunctionTok{summary}\NormalTok{(best.model.fit}\FloatTok{.3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Happiness.Score ~ Economy..GDP.per.Capita. + Family + 
##     Region + Health..Life.Expectancy. + Freedom + Trust..Government.Corruption. + 
##     Dystopia.Residual, data = world.happiness)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.26565 -0.05416 -0.01318  0.04650  0.33787 
## 
## Coefficients:
##                                       Estimate Std. Error t value Pr(>|t|)    
## (Intercept)                            0.39266    0.11474   3.422 0.000812 ***
## Economy..GDP.per.Capita.               0.85909    0.04146  20.720  < 2e-16 ***
## Family                                 1.07638    0.04369  24.639  < 2e-16 ***
## RegionCentral and Eastern Europe      -0.25046    0.07772  -3.223 0.001575 ** 
## RegionEastern Asia                    -0.18892    0.08442  -2.238 0.026789 *  
## RegionLatin America and Caribbean     -0.20510    0.07758  -2.644 0.009117 ** 
## RegionMiddle East and Northern Africa -0.19622    0.07841  -2.502 0.013470 *  
## RegionNorth America                    0.01815    0.10028   0.181 0.856599    
## RegionSoutheastern Asia               -0.03220    0.08270  -0.389 0.697584    
## RegionSouthern Asia                   -0.07456    0.08845  -0.843 0.400631    
## RegionSub-Saharan Africa              -0.21516    0.08762  -2.455 0.015277 *  
## RegionWestern Europe                  -0.11803    0.07470  -1.580 0.116314    
## Health..Life.Expectancy.               1.07428    0.08156  13.171  < 2e-16 ***
## Freedom                                1.12870    0.07505  15.039  < 2e-16 ***
## Trust..Government.Corruption.          1.11602    0.08431  13.237  < 2e-16 ***
## Dystopia.Residual                      0.97672    0.01613  60.569  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.09945 on 142 degrees of freedom
## Multiple R-squared:  0.9932, Adjusted R-squared:  0.9925 
## F-statistic:  1378 on 15 and 142 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{\{}\FunctionTok{qqnorm}\NormalTok{(best.model.fit}\FloatTok{.3}\SpecialCharTok{$}\NormalTok{residuals)}
  \FunctionTok{qqline}\NormalTok{(best.model.fit}\FloatTok{.3}\SpecialCharTok{$}\NormalTok{residuals)\}}
\end{Highlighting}
\end{Shaded}

\includegraphics{R-Happiness-Index-Model_files/figure-latex/unnamed-chunk-25-1.pdf}

\end{document}
